version: '2'
services:
  mysql:
    image: mysql:5.7
#    volumes:
#      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: shush

  keystone:
    build:
      context: ./kbuild
    depends_on:
      - mysql
    image: dizz/dock-os-keystone
    hostname: keystone
    links:
      - mysql
    ports:
      - "35357:35357"
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: shush
      ADMIN_TOKEN: admintokin
      ADMIN_TENANT_NAME: admin
      ADMIN_USER_NAME: admin
      ADMIN_PASSWORD: admin

  horizon:
    build:
      context: ./hbuild
    depends_on:
      - keystone
    image: dizz/dock-os-horizon
    hostname: horizon
    links:
      - keystone
    ports:
      - "80:80"
    environment:
      # KEYSTONE_URL: http://keystone:5000/v3
      KEYSTONE_URL: http://keystone:5000/v2.0
