version: '2'
services:
  mysql:
    image: mysql:latest
#    volumes:
#      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: shush

  keystone:
    depends_on:
      - mysql
    image: dizz/openstack-keystone
    hostname: keystone
    links:
      - mysql
    ports:
      - "35357:35357"
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: shush
      ADMIN_TOKEN: admintokin
      ADMIN_TENANT_NAME: admin
      ADMIN_USER_NAME: admin
      ADMIN_PASSWORD: admin
