version: '2.1'
services:
  mysql:
    image: mysql:5.7
#    volumes:
#      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: shush
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=shush --execute \"show databases;\""
      interval: 10s
      timeout: 10s
      retries: 5


  keystone:
    build:
      context: ./kbuild
    depends_on:
      - mysql
    image: dizz/dock-os-keystone
    hostname: keystone
    links:
      - mysql
    ports:
      - "35357:35357"
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: shush
      ADMIN_TOKEN: admintokin
      ADMIN_TENANT_NAME: admin
      ADMIN_USER_NAME: admin
      ADMIN_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 5

  horizon:
    build:
      context: ./hbuild
    depends_on:
      - keystone
    image: dizz/dock-os-horizon
    hostname: horizon
    links:
      - keystone
    ports:
      - "80:80"
    environment:
      KEYSTONE_URL: http://keystone:5000/v2.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 5
